config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :nomes
  resources :telefones
  get 'configuracao/index'
  post 'services/addressAPI', to: 'configuracao#busca_cep'
  get 'services/selectApHouse', to: 'configuracao#casa_ap'
  resources :enderecos
  namespace :profiles do
    namespace :case_use do
      resources :pacientes
    end
  end
  devise_for :admins
  devise_for :users

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    namespace :pacientes do
      resources :welcomes
    end
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end



  get 'inicio', to: 'site/welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'site/welcome#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/profiles/case_use/paciente.rb
class Profiles::CaseUse::Paciente < ApplicationRecord
end

app/models/users_backoffice/pacientes.rb
module UsersBackoffice::Pacientes
  def self.table_name_prefix
    "users_backoffice_pacientes_"
  end
end

app/models/users_backoffice/pacientes/welcome.rb
class UsersBackoffice::Pacientes::Welcome < ApplicationRecord
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @admins = Admin.all
  end
end

app/controllers/profiles/case_use/pacientes_controller.rb
class Profiles::CaseUse::PacientesController < ApplicationController
  before_action :set_profiles_case_use_paciente, only: %i[ show edit update destroy ]

  # GET /profiles/case_use/pacientes or /profiles/case_use/pacientes.json
  def index
    @profiles_case_use_pacientes = Profiles::CaseUse::Paciente.all
  end

  # GET /profiles/case_use/pacientes/1 or /profiles/case_use/pacientes/1.json
  def show
  end

  # GET /profiles/case_use/pacientes/new
  def new
    @profiles_case_use_paciente = Profiles::CaseUse::Paciente.new
  end

  # GET /profiles/case_use/pacientes/1/edit
  def edit
  end

  # POST /profiles/case_use/pacientes or /profiles/case_use/pacientes.json
  def create
    @profiles_case_use_paciente = Profiles::CaseUse::Paciente.new(profiles_case_use_paciente_params)

    respond_to do |format|
      if @profiles_case_use_paciente.save
        format.html { redirect_to profiles_case_use_paciente_url(@profiles_case_use_paciente), notice: "Paciente was successfully created." }
        format.json { render :show, status: :created, location: @profiles_case_use_paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profiles_case_use_paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/case_use/pacientes/1 or /profiles/case_use/pacientes/1.json
  def update
    respond_to do |format|
      if @profiles_case_use_paciente.update(profiles_case_use_paciente_params)
        format.html { redirect_to profiles_case_use_paciente_url(@profiles_case_use_paciente), notice: "Paciente was successfully updated." }
        format.json { render :show, status: :ok, location: @profiles_case_use_paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profiles_case_use_paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/case_use/pacientes/1 or /profiles/case_use/pacientes/1.json
  def destroy
    @profiles_case_use_paciente.destroy!

    respond_to do |format|
      format.html { redirect_to profiles_case_use_pacientes_url, notice: "Paciente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profiles_case_use_paciente
      @profiles_case_use_paciente = Profiles::CaseUse::Paciente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profiles_case_use_paciente_params
      params.fetch(:profiles_case_use_paciente, {})
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/users_backoffice/pacientes/welcomes_controller.rb
class UsersBackoffice::Pacientes::WelcomesController < ApplicationController
  before_action :set_users_backoffice_pacientes_welcome, only: %i[ show edit update destroy ]

  # GET /users_backoffice/pacientes/welcomes or /users_backoffice/pacientes/welcomes.json
  def index
    @users_backoffice_pacientes_welcomes = UsersBackoffice::Pacientes::Welcome.all
  end

  # GET /users_backoffice/pacientes/welcomes/1 or /users_backoffice/pacientes/welcomes/1.json
  def show
  end

  # GET /users_backoffice/pacientes/welcomes/new
  def new
    @users_backoffice_pacientes_welcome = UsersBackoffice::Pacientes::Welcome.new
  end

  # GET /users_backoffice/pacientes/welcomes/1/edit
  def edit
  end

  # POST /users_backoffice/pacientes/welcomes or /users_backoffice/pacientes/welcomes.json
  def create
    @users_backoffice_pacientes_welcome = UsersBackoffice::Pacientes::Welcome.new(users_backoffice_pacientes_welcome_params)

    respond_to do |format|
      if @users_backoffice_pacientes_welcome.save
        format.html { redirect_to users_backoffice_pacientes_welcome_url(@users_backoffice_pacientes_welcome), notice: "Welcome was successfully created." }
        format.json { render :show, status: :created, location: @users_backoffice_pacientes_welcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @users_backoffice_pacientes_welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_backoffice/pacientes/welcomes/1 or /users_backoffice/pacientes/welcomes/1.json
  def update
    respond_to do |format|
      if @users_backoffice_pacientes_welcome.update(users_backoffice_pacientes_welcome_params)
        format.html { redirect_to users_backoffice_pacientes_welcome_url(@users_backoffice_pacientes_welcome), notice: "Welcome was successfully updated." }
        format.json { render :show, status: :ok, location: @users_backoffice_pacientes_welcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @users_backoffice_pacientes_welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_backoffice/pacientes/welcomes/1 or /users_backoffice/pacientes/welcomes/1.json
  def destroy
    @users_backoffice_pacientes_welcome.destroy!

    respond_to do |format|
      format.html { redirect_to users_backoffice_pacientes_welcomes_url, notice: "Welcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_backoffice_pacientes_welcome
      @users_backoffice_pacientes_welcome = UsersBackoffice::Pacientes::Welcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def users_backoffice_pacientes_welcome_params
      params.require(:users_backoffice_pacientes_welcome).permit(:index)
    end
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
    @users = User.all
    @email = Email.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/profiles/case_use/pacientes_helper.rb
module Profiles::CaseUse::PacientesHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/users_backoffice/pacientes/welcomes_helper.rb
module UsersBackoffice::Pacientes::WelcomesHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users_backoffice/pacientes/welcomes/_form.html.erb
<%= form_with(model: users_backoffice_pacientes_welcome) do |form| %>
  <% if users_backoffice_pacientes_welcome.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(users_backoffice_pacientes_welcome.errors.count, "error") %> prohibited this users_backoffice_pacientes_welcome from being saved:</h2>

      <ul>
        <% users_backoffice_pacientes_welcome.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.text_field :index %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users_backoffice/pacientes/welcomes/_welcome.html.erb
<div id="<%= dom_id welcome %>">
  <p>
    <strong>Index:</strong>
    <%= welcome.index %>
  </p>

</div>

app/views/users_backoffice/pacientes/welcomes/edit.html.erb
<h1>Editing welcome</h1>

<%= render "form", users_backoffice_pacientes_welcome: @users_backoffice_pacientes_welcome %>

<br>

<div>
  <%= link_to "Show this welcome", @users_backoffice_pacientes_welcome %> |
  <%= link_to "Back to welcomes", users_backoffice_pacientes_welcomes_path %>
</div>

app/views/users_backoffice/pacientes/welcomes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Welcomes</h1>

<div id="users_backoffice_pacientes_welcomes">
  <% @users_backoffice_pacientes_welcomes.each do |users_backoffice_pacientes_welcome| %>
    <%= render users_backoffice_pacientes_welcome %>
    <p>
      <%= link_to "Show this welcome", users_backoffice_pacientes_welcome %>
    </p>
  <% end %>
</div>

<%= link_to "New welcome", new_users_backoffice_pacientes_welcome_path %>

app/views/users_backoffice/pacientes/welcomes/new.html.erb
<h1>New welcome</h1>

<%= render "form", users_backoffice_pacientes_welcome: @users_backoffice_pacientes_welcome %>
<%= render 'users_backoffice/welcome/user_siderbar' %>

<br>

<div>
  <%= link_to "Back to welcomes", users_backoffice_pacientes_welcomes_path %>
</div>

app/views/users_backoffice/pacientes/welcomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @users_backoffice_pacientes_welcome %>

<div>
  <%= link_to "Edit this welcome", edit_users_backoffice_pacientes_welcome_path(@users_backoffice_pacientes_welcome) %> |
  <%= link_to "Back to welcomes", users_backoffice_pacientes_welcomes_path %>

  <%= button_to "Destroy this welcome", @users_backoffice_pacientes_welcome, method: :delete %>
</div>