config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :nomes
  resources :telefones
  get 'configuracao/index'
  post 'services/addressAPI', to: 'configuracao#busca_cep'
  get 'services/selectApHouse', to: 'configuracao#casa_ap'
  resources :enderecos
  namespace :profiles do
    namespace :case_use do
      resources :pacientes
    end
  end
  devise_for :admins
  devise_for :users

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    namespace :pacientes do
      resources :welcomes
    end
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end



  get 'inicio', to: 'site/welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'site/welcome#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/telefone.rb
class Telefone < ApplicationRecord
end

app/controllers/telefones_controller.rb
class TelefonesController < ApplicationController
  before_action :set_telefone, only: %i[ show edit update destroy ]

  # GET /telefones or /telefones.json
  def index
    @telefones = Telefone.all
  end

  # GET /telefones/1 or /telefones/1.json
  def show
  end

  # GET /telefones/new
  def new
    @telefone = Telefone.new
  end

  # GET /telefones/1/edit
  def edit
  end

  # POST /telefones or /telefones.json
  def create
    @telefone = Telefone.new(telefone_params)

    respond_to do |format|
      if @telefone.save
        format.html { redirect_to telefone_url(@telefone), notice: "Telefone was successfully created." }
        format.json { render :show, status: :created, location: @telefone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefones/1 or /telefones/1.json
  def update
    respond_to do |format|
      if @telefone.update(telefone_params)
        format.html { redirect_to telefone_url(@telefone), notice: "Telefone was successfully updated." }
        format.json { render :show, status: :ok, location: @telefone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefones/1 or /telefones/1.json
  def destroy
    @telefone.destroy!

    respond_to do |format|
      format.html { redirect_to telefones_url, notice: "Telefone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telefone
      @telefone = Telefone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def telefone_params
      params.require(:telefone).permit(:ddd, :telefone)
    end
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/views/telefones/_form.html.erb
<%= form_with(model: telefone) do |form| %>
  <% if telefone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(telefone.errors.count, "error") %> prohibited this telefone from being saved:</h2>

      <ul>
        <% telefone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ddd, style: "display: block" %>
    <%= form.number_field :ddd %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.number_field :telefone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/telefones/_telefone.html.erb
<div id="<%= dom_id telefone %>">
  <p>
    <strong>Ddd:</strong>
    <%= telefone.ddd %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= telefone.telefone %>
  </p>

</div>

app/views/telefones/_telefone_bloco.html.erb
<h2>Whatsapp do meu consultório</h2>
<div class="form-group">
  <label for="example-tel-input" class="form-control-label">DDD</label>
  <input class="form-control" type="number" placeholder="coloque aqui o seu DDD" id="tel-input">
  <label for="example-tel-input" class="form-control-label">Número do Whatsapp</label>
  <input class="form-control" type="number" placeholder="Coloque aqui o seu whatsapp" id="tel-input">
</div>

app/views/telefones/edit.html.erb
<h1>Editing telefone</h1>

<%= render "form", telefone: @telefone %>

<br>

<div>
  <%= link_to "Show this telefone", @telefone %> |
  <%= link_to "Back to telefones", telefones_path %>
</div>

app/views/telefones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Telefones</h1>

<div id="telefones">
  <% @telefones.each do |telefone| %>
    <%= render telefone %>
    <p>
      <%= link_to "Show this telefone", telefone %>
    </p>
  <% end %>
</div>

<%= link_to "New telefone", new_telefone_path %>

app/views/telefones/new.html.erb
<h1>New telefone</h1>

<%= render "form", telefone: @telefone %>

<br>

<div>
  <%= link_to "Back to telefones", telefones_path %>
</div>

app/views/telefones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @telefone %>

<div>
  <%= link_to "Edit this telefone", edit_telefone_path(@telefone) %> |
  <%= link_to "Back to telefones", telefones_path %>

  <%= button_to "Destroy this telefone", @telefone, method: :delete %>
</div>